import { CATEGORY_LABELS, type Analysis, type RepositoryInfo } from "@/types/analysis";

export function analysisToMarkdown(
  repo: RepositoryInfo,
  analysis: Analysis,
  filesAnalyzed: number,
  truncated: boolean
): string {
  const lines: string[] = [];
  lines.push(`# RepoPilot Analysis`);
  lines.push("");
  lines.push(`Repository: [${repo.owner}/${repo.name}](${repo.htmlUrl})`);
  if (repo.description) lines.push(`> ${repo.description}`);
  lines.push("");
  lines.push(`## Summary`);
  lines.push("");
  lines.push(analysis.summary);
  lines.push("");
  lines.push(`**Overall Score:** ${analysis.overallScore}/100`);
  lines.push("");

  for (const [key, label] of Object.entries(CATEGORY_LABELS)) {
    const category = analysis.categories[key as keyof typeof analysis.categories];
    lines.push(`## ${label} (${category.score}/100)`);
    lines.push("");
    lines.push(`### Findings`);
    lines.push("");
    if (category.findings.length === 0) lines.push("- None reported.");
    for (const f of category.findings) lines.push(`- ${f}`);
    lines.push("");
    lines.push(`### Recommendations`);
    lines.push("");
    if (category.recommendations.length === 0) lines.push("- None reported.");
    for (const r of category.recommendations) lines.push(`- ${r}`);
    lines.push("");
  }

  lines.push(`## Priority Actions`);
  lines.push("");
  if (analysis.priorityActions.length === 0) lines.push("- None reported.");
  analysis.priorityActions.forEach((a, i) => lines.push(`${i + 1}. ${a}`));
  lines.push("");

  lines.push(`## Limitations`);
  lines.push("");
  if (truncated) {
    lines.push(
      `- Only ${filesAnalyzed} files were selected because the repository exceeded the configured analysis limit. This report reflects a representative subset, not the entire repository.`
    );
  } else {
    lines.push(`- ${filesAnalyzed} files were analyzed.`);
  }
  for (const l of analysis.limitations) lines.push(`- ${l}`);
  lines.push("");
  lines.push(`_Generated by RepoPilot, an open-source AI developer tool._`);
  return lines.join("\n");
}
